### GET request to example server
POST http://localhost:8081/orders

{
	"user_id" : 1,
	"event_id" : 5
}

###
GET http://localhost:8081/orders/2

###
GET http://localhost:8081/orders/

###
GET http://localhost:8081/orders/user/7